// src/components/blocks/main/MainAside.tsx
import {Link} from "react-router-dom";

import {Menu} from "../../../types/menu.ts";

import menuItems from "../../../data/main/menuAside.ts";

import Logo from "../../../assets/images/Logo.tsx";

function MainAside() {


    return (
        <aside className="menu">
            <Link to="/" className="menu__logo button-width-svg flex flex-align-center">
                <Logo/>
                <p className="h4">veFox</p>
            </Link>

            <ul className="menu__list">
                {menuItems.map((item: Menu) => (
                    <li key={item.title} className="menu__item">
                        <button className="menu__btn flex flex-align-center recolor-svg hover-color-accent text-nowrap"
                                type="button"
                        >
                            <item.icon style={{fill: 'none'}}></item.icon>
                            <span>{item.title}</span>
                        </button>
                    </li>
                ))}
            </ul>
        </aside>
    );
}

export default MainAside;

// src/components/blocks/main/MainAside.vue
<script setup lang="ts">

import menuItems from "../../../data/main/menuAside.ts";

import Logo from "../../../assets/images/Logo.vue";


</script>

<template>

  <aside class="menu">
    <RouterLink to="/" class="menu__logo button-width-svg flex flex-align-center">
      <Logo/>
      <p class="h4">veFox</p>
    </RouterLink>

    <ul class="menu__list">
      <li class="menu__item"
          v-for="(item, index) in menuItems"
          :key="index"
      >
        <button class="menu__btn flex flex-align-center recolor-svg hover-color-accent text-nowrap" type="button">
          <component :is="item.icon" style="fill: none"/>
          <span>{{item.title}}</span>
        </button>
      </li>
    </ul>
  </aside>

</template>
