// src/components/blocks/main/MainContent.vue
<script setup lang="ts">

import MainHeader from "./MainHeader.vue";

const test = Array.from({length: 50})

</script>

<template>

  <div class="main__right position-relative">
    <MainHeader/>

    <div class="main__content">
      <div v-for="i in test">привет</div>
    </div>
  </div>

</template>

// src/components/blocks/main/MainContent.tsx


import MainHeader from "./MainHeader.tsx";
import MainHomePage from "./contentPages/MainHomePage.tsx";

function MainContent() {


    return (
        <div className="main__right position-relative">
            <MainHeader/>

            <div className="main__content">
                <MainHomePage/>
            </div>
        </div>
    );
}

export default MainContent;
