// src/components/blocks/main/MainHeader.tsx
import React, {useRef, useState} from "react";

import CrossIcon from "../../../assets/images/icons/CrossIcon.tsx";
import SearchIcon from "../../../assets/images/icons/SearchIcon.tsx";

import avatarImage from "../../../assets/images/аватар.webp";

function MainHeader() {
    const [searchText, setSearchText] = useState('')

    const inputRef = useRef<HTMLInputElement>(null)


    const handleSearchText = (event: React.ChangeEvent<HTMLInputElement>): void => {
        setSearchText(event.target.value)
    }

    const clearSearchText = (): void => {
        setSearchText('')
        inputRef.current?.focus()
    }

    return(
        <header className="header flex flex-align-center flex-justify-center">
            <div className="header__search flex overflow-hidden position-relative">
                <input className="header__input input"
                       ref={inputRef}
                       value={searchText}
                       onChange={handleSearchText}
                       type="text"
                       placeholder="Введите запрос"
                />

                <button className="header__btn flex-center recolor-svg"
                        type="button"
                        aria-label="Поиск"
                        title="Поиск"
                >
                    <SearchIcon/>
                </button>
                {searchText && (
                    <button
                        className="header__clear recolor-svg position-absolute button-width-svg flex-center hover-color-accent"
                        type="button"
                        aria-label="Очистить"
                        title="Очистить"
                        onClick={clearSearchText}
                    >
                        <CrossIcon/>
                    </button>
                )}
            </div>

            <div className="header__avatar img-container position-absolute cursor-pointer"
                 title="user"
            >
                <img src={avatarImage} alt="user"/>
            </div>
        </header>
    )
}

export default MainHeader;

// src/components/blocks/main/MainHeader.vue
<script setup lang="ts">
import {ref} from "vue";

import CrossIcon from "../../../assets/images/icons/CrossIcon.vue";
import SearchIcon from "../../../assets/images/icons/SearchIcon.vue";

import useSearchStore from "../../../store/useSearchStore.ts";
const searchStore = useSearchStore();

const inputElement = ref<HTMLInputElement | null>(null)

const clearSearchText = () => {
  searchStore.searchText = ''

  inputElement.value?.focus()
}

</script>

<template>

  <header class="header flex flex-align-center flex-justify-center">
    <div class="header__search flex overflow-hidden position-relative">
      <input class="header__input input"
             v-model="searchStore.searchText"
             ref="inputElement"
      >
      <button class="header__btn flex-center recolor-svg"
              type="button"
              aria-label="Поиск"
              title="Поиск"
      >
        <SearchIcon/>
      </button>

      <button class="header__clear recolor-svg position-absolute button-width-svg flex-center hover-color-accent"
              type="button"
              aria-label="Очистить"
              title="Очистить"
              @click="clearSearchText"
      >
        <CrossIcon/>
      </button>
    </div>

    <div class="header__avatar img-container position-absolute cursor-pointer" title="user">
      <img src="../../../assets/images/аватар.webp" alt="user">
    </div>
  </header>

</template>
